### ISSUE TITLE
Setting cell labels and image

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#18]
I'm struggling to get the cell UILabels and UIImageView to update with the appropriate text and images, and I'm not sure what I'm doing wrong. 

I am trying to follow the guide at https://www.ralfebert.de/ios-examples/uikit/uitableviewcontroller/custom-cells/ (see sections 11 and 12)

The movie data is correctly loading. I can, for example, `print(movie.trackName)` and have the correct data print out. There are no errors or warnings. 

But even when I pass in a hard coded value (as below with "Movie Title") the text of the label does not update. The only way I can get any text or image to show is if I edit the text in the Attributes Inspector, which is obviously not a solution. Any suggestions?

```
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let movie = movies[indexPath.row]
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "movieTableViewCell", for: indexPath) as! MovieTableViewCell
        
        cell.movieNameLabel?.text = "Movie Title" //movie.trackName
        cell.genreNameLabel?.text = movie.primaryGenreName
        cell.movieCellImage?.image = UIImage(named: "popcorn")
        
        return cell
    }
```

**Comment by hbennett766** [comment]
There are many possibilities for what could be going on here. First, some gut checks:

1. The IBOutlets in your `MovieTableViewCell` are hooked up and active. The dots next to `movieNameLabel`, `genreNameLabel`, and `movieCellImage` should be filled in.

2. The method `numberOfRows inSection` defaults to returning 0. You changed that to return  `movies.count` instead.

3. The labels and image view are instantiated at the time you set their properties. The fact that there are question marks after each cell property means that those properties are optional. I would recommend force unwrapping the IBOutlets in your `MovieTableViewCell` class, e.g.

```
@IBOutlet weak var movieNameLabel: UILabel!
```

Then, in use, you won't have to include that question mark every time you reference the cell properties. Force unwrapping is ok here because as a developer, we want to know (via an app crash in development) if those properties on the cell are not being instantiated. If your app crashes after changing those outlets to a force unwrap, then your cell isn't being properly instantiated.

Lmk if any of these was your issue! If the answer is "none of the above", can you make sure your assignment 3 repo is up to date? I'll can pull down your code and figure it out firsthand.

**Comment by landonjmitchell** [comment]
Thanks for the tips! One of my my table view cell classes was incorrectly named. The cell data updates are working now. Unfortunately, now I'm getting a keyNotFound error for one of my table view searches. I can see the JSON results, so not sure what the error is about. My repo is up-to-date if you have a chance to take a look. (not all functionality is implemented yet, particularly the detail view).

**Comment by hbennett766** [comment]
`keyNotFound` means that the data structure of your model object doesn't match the data structure of the JSON. I'll go figure out what exactly it's yelling at you about.

**Comment by hbennett766** [comment]
So I reproduced the error message you're getting. Let's debug it. First let's read the whole message. It's actually pretty helpful, once you get past how verbose it is.

```
keyNotFound(CodingKeys(stringValue: "trackName", intValue: nil), 
Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil),
 _JSONKey(stringValue: "Index 1", intValue: 1)], debugDescription: 
"No value associated with key CodingKeys(stringValue: \"trackName\", intValue: nil) 
(\"trackName\").", underlyingError: nil))
```

The debug description is the clue here. It's telling us that there's no value associated with the coding key "trackName". In other words, the model object is expecting a `String` value, and the JSON value is `nil`.

If we look at the `Movie` object, `trackName` is non-optional. That's essentially telling the app that we know _for a fact_ that we will get a track name back with each and every movie. While this seems like it should be a given, we don't control the iTunes API. As a general rule of thumb, we need to be as flexible as possible with the data structure we're creating from JSON we don't control.

Make that `trackName` property an optional `String` instead of a guaranteed `String`, and you're good to go. The model object can then accept `nil` as a valid value for that key.

**Comment by hbennett766** [comment]
Unrelated comment:

In Swift, we never explicitly compare `Bool` values to `true` or `false`. Instead of

```
if movie.hasITunesExtras == true {
```

we should just write

```
if movie.hasITunesExtras {
```

You can usually tell whether you're writing good Swift by how much reading your code sounds like plain English. "If movie has ITunes extras is true" vs "If movie has ITunes extras".

See #19 for more info on Swifty Bools
