### ISSUE TITLE
Custom TableViewControllers

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#20]
I've made my tableview controllers and tried to connect them to my storyboard but can't get them to show up as an option in Main.storyboard in the identity inspector when I select the Table View Controller button in the bar above the view. I've implemented the methods that it seems like we should implement based on looking at ListViewController. I'm not sure what's wrong.

**Comment by hbennett766** [comment]
It looks like your two view controllers are set as class type `UIViewController`, not `UITableViewController`. While that will work fine in code, the storyboard objects that are of type `UITableViewController` won't recognize that your regular `UIViewController`s are implementing table view delegate and data source methods.

I'd recommend changing the class type to `UTableViewController`:

```
class RomanceTableViewController: UITableViewController {
```

This will give you some compiler errors.

1. You will need to add the `override` keyword before all of your table view methods.
2. You will need to delete the `tableView` IBOutlet, because table view controllers come with one already. You access it like any other class level property: `tableView.whatever` or if you need to use an explicit self, `self.tableView.whatever`
3. You will need to remove the explicit class conformations to `UITableViewDelegate` and `UITableViewDataSource` in your extensions. `UITableViewController`s conform to both of those protocols out of the box.
4. You will need to delete the two lines of code inside `viewDidLoad` where you set the `dataSource` and the `delegate` equal to `self`. Those are also done for you behind the scenes in a table view controller.

**Comment by westminsterabi** [comment]
Okay, then I'm really confused as to how things are working [here](https://github.com/uchicago-mobi/podcastpicker/blob/master/PodcastPicker/ListViewController.swift), since this is what we did in class.

**Comment by hbennett766** [comment]
The list view controller object in that project's storyboard is a `UIViewController` with a `UITableView` object dragged into it manually and arranged with layout constraints.

The view controller objects in your storyboard are type `UITableViewController`, where you automatically get the table view object built in.

The type of view controller in storyboard has to match the type of the view controller in code. So in the podcast example, both storyboard and code use `UIViewController`s. Yours didn't match, so I suggested you switch over to using both `UITableViewController`s. My reasoning is that I prefer using as many built-in tools as possible. We get more "given" to us when we use a `UITableViewController`. But either way can be argued for, and both are "correct".

If you would like, you can use a `UIViewController` that conforms to table view protocols and has a table view object. To do that, you would have to replace your storyboard table view controllers with instances of `UIViewController`.

Does that "matching of the object types" make more sense now?

**Comment by hbennett766** [comment]
I assume the reason @chelseatroy went the way she did with the `UIViewController` containing a table view was to expose the logic of a table view controller. Because you have to code more of the base functionality in, you can see things like the explicit protocol conformance to `UITableViewDelegate` and `UITableViewDataSource`.

**Comment by westminsterabi** [comment]
Yup that makes sense!
